extra types: fix C type in plot time
AllenDang/cimgui-go pull request #106
Opened 2023-01-23 12:43 UTC by gucio321

fix #105

2023-01-23 13:01 UTC, nullptr-ref requested changes

2023-01-23 13:01 UTC, nullptr-ref commented on extra_types.h
> +typedef long long xlong;
This should also be xxlong

2023-01-23 13:02 UTC, gucio321 commented on extra_types.h
> +typedef long long xlong;
ops, right :smile:
thank you

2023-01-23 13:21 UTC, nullptr-ref requested changes
As suspected, when renaming xlong to xulong it broke other entries of "xlong" in the following 2 files:

input_text.go
cimgui_funcs.go

You have to also replace them there. I'll attach the already replaced files.

2023-01-23 13:21 UTC, nullptr-ref commented on extra_types.h
>  typedef unsigned long xulong;
This doesn't seem right, let me check. Think this will break a whole lot of stuff.

2023-01-23 13:26 UTC, nullptr-ref approved these changes
All good now :)

2023-01-23 13:28 UTC, nullptr-ref approved these changes

2023-01-25 16:14 UTC, AllenDang approved these changes
LGTM

2023-01-25 16:14 UTC, merged